Repository Team-KeepGoEat/KeepGoEat-AOS, pull requests merged in 2023-05, with the labels that each got.

#233 [mod] 강제 업데이트 컨벤션 수정
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#234 [refactor] 믹스패널 스크린 타임 기록 관련 코드 리팩토링 및 패키지 정리
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/java/org/keepgoeat/presentation/base/screen/BindingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/base/screen/BindingBottomSheetDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/base/screen/BindingDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/base/screen/BindingFragment.kt
  app/src/main/java/org/keepgoeat/presentation/base/screen/MixpanelActivity.kt
  app/src/main/java/org/keepgoeat/presentation/base/screen/MixpanelBottomSheetDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/base/viewmodel/BaseViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/base/viewmodel/MixpanelViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/common/WebViewActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDeleteBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalKeepBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeForceUpdateDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/model/WithdrawReason.kt
  app/src/main/java/org/keepgoeat/presentation/my/AccountInfoActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/LogoutDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/my/ServiceIntroActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/archive/ArchivedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/archive/GoalDeleteDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/my/withdraw/WithdrawActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/withdraw/WithdrawDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/res/layout/dialog_goal_delete.xml
Labels: 🐹 영진 🐹, ✂refactor✂

#235 [refactor] 이모지 입력되었을 때 2글자로 인식되는 오류 수정
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/my/withdraw/WithdrawReasonAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/type/WithdrawReason.kt
  app/src/main/java/org/keepgoeat/util/BindingAdatper.kt
  app/src/main/java/org/keepgoeat/util/extension/StringExt.kt
  app/src/main/res/layout/activity_goal_setting.xml
Labels: 🐶 유빈 🐶, ✂refactor✂

#237 [mod] 온보딩 중도 이탈 플로우 개선
  app/src/main/java/org/keepgoeat/data/model/response/ResponseAuth.kt
  app/src/main/java/org/keepgoeat/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/domain/model/AuthInfo.kt
  app/src/main/java/org/keepgoeat/domain/repository/AuthRepository.kt
  app/src/main/java/org/keepgoeat/domain/type/SignType.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
Labels: 🐹 영진 🐹, 🛠 mod 🛠

#240 [fix] 믹스패널 유저 프로필 안 보이는 이슈 해결
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/java/org/keepgoeat/util/mixpanel/MixpanelProvider.kt
Labels: 🕷 fix 🕷, 🐶 유빈 🐶

#244 [fix] 토큰 갱신 시 크래시가 발생하는 버그 수정
  app/build.gradle
  app/src/main/java/org/keepgoeat/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/keepgoeat/di/NetworkModule.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  build.gradle
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#245 [fix] 토큰 갱신 요청 전 reponse를 close하지 않아 크래시가 발생하는 버그 수정
  app/build.gradle
  app/src/main/java/org/keepgoeat/data/interceptor/AuthInterceptor.kt
  app/src/main/res/values/strings.xml
Labels: 🕷 fix 🕷, 🐹 영진 🐹
