Repository Team-KeepGoEat/KeepGoEat-AOS, pull requests merged in 2023-01, with the labels that each got.

#7 [feat] 카드 상세뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/domain/model/GoalSticker.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailTestActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalStickerListAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/type/EatingType.kt
  app/src/main/java/org/keepgoeat/presentation/type/RecyclerLayoutType.kt
  app/src/main/java/org/keepgoeat/util/ItemDecorationUtil.kt
  app/src/main/java/org/keepgoeat/util/extension/IntExt.kt
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_default_green_sticker.xml
  app/src/main/res/drawable/ic_default_orange_sticker.xml
  app/src/main/res/drawable/ic_eating_less_tag_minus.xml
  app/src/main/res/drawable/ic_eating_more_tag_plus.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_snail_green_sticker.xml
  app/src/main/res/drawable/ic_snail_orange_sticker.xml
  app/src/main/res/drawable/ic_storage.xml
  app/src/main/res/drawable/shape_border_gray_radius_8.xml
  app/src/main/res/drawable/shape_border_radius_4.xml
  app/src/main/res/drawable/shape_border_radius_8.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_goal_detail_test.xml
  app/src/main/res/layout/item_goal_sticker.xml
  app/src/main/res/layout/view_eating_tag.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#13 [feat] 목표 설정뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailTestActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/java/org/keepgoeat/util/extension/ContextExt.kt
  app/src/main/res/color/selector_complete_button_color.xml
  app/src/main/res/color/selector_complete_button_text_color.xml
  app/src/main/res/drawable/selector_edittext_background.xml
  app/src/main/res/layout/activity_goal_setting.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#16 [feat] 크래시 방지 처리 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/App.kt
Labels: 🐹 영진 🐹, ✨ feat ✨

#18 [feat] 앱 로고 및 이름 적용
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#19 [feat] 목표 보관 바텀 시트 구현
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailTestActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/keep/GoalKeepBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/type/EatingType.kt
  app/src/main/java/org/keepgoeat/util/binding/BindingBottomSheetDialogFragment.kt
  app/src/main/res/drawable/ic_keep.xml
  app/src/main/res/drawable/ic_snail_green_cheer_left.xml
  app/src/main/res/drawable/ic_snail_orange_cheer_left.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_goal_setting.xml
  app/src/main/res/layout/dialog_bottom_goal_keep.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#21 [mod] 마진 사이즈 수정
  app/src/main/java/org/keepgoeat/util/extension/ContextExt.kt
  app/src/main/res/layout/activity_goal_setting.xml
Labels: 🐹 영진 🐹, 🛠 mod 🛠, 💫 chore 💫

#26 [init] 서버통신 예외처리 기초세팅
  app/src/main/java/org/keepgoeat/data/ApiResponse.kt
  app/src/main/java/org/keepgoeat/data/ApiResult.kt
  app/src/main/java/org/keepgoeat/data/datasource/remote/DummyDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseListResult.kt
  app/src/main/java/org/keepgoeat/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/DummyService.kt
  app/src/main/java/org/keepgoeat/domain/repository/DummyRepository.kt
  app/src/main/java/org/keepgoeat/presentation/dummy/DummyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/dummy/DummyViewModel.kt
  app/src/main/java/org/keepgoeat/util/ApiUtil.kt
  app/src/main/java/org/keepgoeat/util/UiState.kt
Labels: 🐹 영진 🐹, 🌿 init 🌿

#22 [feat] 홈 화면 뷰 UI 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/home/MyGoalInfo.kt
  app/src/main/java/org/keepgoeat/presentation/type/HomeBtnType.kt
  app/src/main/java/org/keepgoeat/presentation/type/HomeGoalViewType.kt
  app/src/main/res/drawable/background_cheer_msg.xml
  app/src/main/res/drawable/background_goal_info.xml
  app/src/main/res/drawable/background_goal_list.xml
  app/src/main/res/drawable/background_goal_tag.xml
  app/src/main/res/drawable/background_home_bottom.xml
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_check_green.xml
  app/src/main/res/drawable/ic_check_orange.xml
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_right.xml
  app/src/main/res/drawable/img_plate_gray_view.xml
  app/src/main/res/drawable/img_snail_orange_cheer.xml
  app/src/main/res/drawable/img_snail_orange_hungry.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_add_goal.xml
  app/src/main/res/layout/item_home_header.xml
  app/src/main/res/layout/item_home_text.xml
  app/src/main/res/layout/item_my_goal.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#28 [feat] 스플래시 뷰 구현
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/res/drawable-hdpi/img_logo.png
  app/src/main/res/drawable-hdpi/img_snail_splash.png
  app/src/main/res/drawable-mdpi/img_logo.png
  app/src/main/res/drawable-mdpi/img_snail_splash.png
  app/src/main/res/drawable-xhdpi/img_logo.png
  app/src/main/res/drawable-xhdpi/img_snail_splash.png
  app/src/main/res/drawable-xxhdpi/img_logo.png
  app/src/main/res/drawable-xxhdpi/img_snail_splash.png
  app/src/main/res/drawable-xxxhdpi/img_logo.png
  app/src/main/res/drawable-xxxhdpi/img_snail_splash.png
  app/src/main/res/layout/activity_splash.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#31 [feat] 로그인 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/service/SignService.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/shape_border_radius_6.xml
  app/src/main/res/drawable/sign_keepgoeat.xml
  app/src/main/res/drawable/snail_green_spoon.xml
  app/src/main/res/drawable/snail_orange_spoon.xml
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/values/strings.xml
  settings.gradle
Labels: 🐰 다은 🐰, ✨ feat ✨

#25 [feat] 온보딩 뷰 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/OnBoardingViewType.kt
  app/src/main/res/drawable-hdpi/img_onboarding_1.png
  app/src/main/res/drawable-hdpi/img_onboarding_2.png
  app/src/main/res/drawable-hdpi/img_onboarding_3.png
  app/src/main/res/drawable-mdpi/img_onboarding_1.png
  app/src/main/res/drawable-mdpi/img_onboarding_2.png
  app/src/main/res/drawable-mdpi/img_onboarding_3.png
  app/src/main/res/drawable-xhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xhdpi/img_onboarding_2.png
  app/src/main/res/drawable-xhdpi/img_onboarding_3.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_2.png
  app/src/main/res/drawable-xxhdpi/img_onboarding_3.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_1.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_2.png
  app/src/main/res/drawable-xxxhdpi/img_onboarding_3.png
  app/src/main/res/drawable/default_dot.xml
  app/src/main/res/drawable/selected_dot.xml
  app/src/main/res/drawable/tab_selector.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#33 [refactor] 홈 뷰 리팩토링
  app/src/main/java/org/keepgoeat/domain/model/HomeMyGoal.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/HomeGoalViewType.kt
  app/src/main/res/drawable/background_goal_tag.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_home_header.xml
  app/src/main/res/layout/item_home_text.xml
  app/src/main/res/layout/item_my_goal.xml
Labels: 🐶 유빈 🐶, ✂refactor✂

#36 [feat] 마이페이지 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/domain/model/AchievedGoal.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalStickerListAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyHeaderAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/EatingType.kt
  app/src/main/java/org/keepgoeat/util/BindingAdatper.kt
  app/src/main/java/org/keepgoeat/util/ItemDecorationUtil.kt
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/item_home_goal.xml
  app/src/main/res/layout/item_my_goal.xml
  app/src/main/res/layout/layout_my_header.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#38 [feat] 홈 뷰 화면 전환 구현
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/res/layout/item_my_goal.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#39 [chore] 홈 레이아웃 아이디 설정
  app/src/main/res/layout/item_home_goal.xml
Labels: 🐶 유빈 🐶, 💫 chore 💫

#42 [feat] 홈 뷰, 마이페이지 뷰 화면 전환
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
Labels: 🐶 유빈 🐶, ✨ feat ✨

#45 [fix] 마이페이지 목표 RecyclerView 깜박임 버그 수정
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#48 [fix] 린트 오류 해결
  app/src/main/java/org/keepgoeat/util/BindingAdatper.kt
  app/src/main/java/org/keepgoeat/util/extension/IntExt.kt
  app/src/main/res/values/strings.xml
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#37 [feat] 로그인 뷰 자동 로그인 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/service/SignService.kt
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignSharedPreferences.kt
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#49 [feat] 홈 뷰 배경 이미지 추가
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/type/HomeBackgroundType.kt
  app/src/main/java/org/keepgoeat/util/BindingAdatper.kt
  app/src/main/res/drawable-hdpi/img_home_background_evening.png
  app/src/main/res/drawable-hdpi/img_home_background_morning.png
  app/src/main/res/drawable-hdpi/img_home_background_night.png
  app/src/main/res/drawable-mdpi/img_home_background_evening.png
  app/src/main/res/drawable-mdpi/img_home_background_morning.png
  app/src/main/res/drawable-mdpi/img_home_background_night.png
  app/src/main/res/drawable-xhdpi/img_home_background_evening.png
  app/src/main/res/drawable-xhdpi/img_home_background_morning.png
  app/src/main/res/drawable-xhdpi/img_home_background_night.png
  app/src/main/res/drawable-xxhdpi/img_home_background_evening.png
  app/src/main/res/drawable-xxhdpi/img_home_background_morning.png
  app/src/main/res/drawable-xxhdpi/img_home_background_night.png
  app/src/main/res/drawable-xxxhdpi/img_home_background_evening.png
  app/src/main/res/drawable-xxxhdpi/img_home_background_morning.png
  app/src/main/res/drawable-xxxhdpi/img_home_background_night.png
  app/src/main/res/drawable/ic_mypage.xml
  app/src/main/res/drawable/ic_mypage_white.xml
  app/src/main/res/layout/item_home_header.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#54 [mod] #53 로그인 뷰 말풍선 이미지 추가
  app/src/main/res/drawable/background_sign_box.xml
  app/src/main/res/layout/activity_sign.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#57 [feat] 목표 삭제 다이얼로그 뷰 구현
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDeleteBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalKeepBottomDialogFragment.kt
  app/src/main/res/drawable/ic_trash.xml
  app/src/main/res/layout/dialog_bottom_goal_delete.xml
  app/src/main/res/layout/dialog_bottom_goal_keep.xml
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#59 [feat] #58 마이페이지 툴바 추가
  app/src/main/res/layout/activity_my.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#60 [mod] 홈 뷰 배경화면 추가, 스크롤 영역 설정
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/HomeGoalViewType.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_home_header.xml
Labels: 🐶 유빈 🐶, 🛠 mod 🛠

#65 [add] base url 추가
  .github/workflows/pr_builder.yml
  app/build.gradle
  app/src/main/java/org/keepgoeat/di/NetworkModule.kt
Labels: 🐹 영진 🐹, 😘 add 😘

#67 [mod] 홈 뷰, 목표 상세뷰 연결
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/home/MyGoalInfo.kt
  app/src/main/res/drawable/background_goal_info.xml
  app/src/main/res/layout/item_home_goal.xml
  app/src/main/res/values/colors.xml
Labels: 🐶 유빈 🐶, 🛠 mod 🛠

#52 [mod] 안드로이드 12 스플래시 대응
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/res/values/themes.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#72 [feat] 홈 뷰 서버 통신
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseHome.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/di/RepositoryModule.kt
  app/src/main/java/org/keepgoeat/di/ServiceModule.kt
  app/src/main/java/org/keepgoeat/domain/model/HomeGoal.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_home_goal.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#75 [feat] 목표 추가 api 연동
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/request/RequestGoalContent.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalContent.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/res/layout/activity_goal_setting.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#77 [feat] 마이페이지 api 연동
  app/src/main/java/org/keepgoeat/data/datasource/remote/MyDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseMy.kt
  app/src/main/java/org/keepgoeat/data/repository/MyRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/MyService.kt
  app/src/main/java/org/keepgoeat/di/NetworkModule.kt
  app/src/main/java/org/keepgoeat/di/RepositoryModule.kt
  app/src/main/java/org/keepgoeat/di/ServiceModule.kt
  app/src/main/java/org/keepgoeat/domain/model/MyGoal.kt
  app/src/main/java/org/keepgoeat/domain/repository/MyRepository.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/EatingType.kt
  app/src/main/java/org/keepgoeat/presentation/type/SortType.kt
  app/src/main/java/org/keepgoeat/util/BindingAdatper.kt
  app/src/main/res/layout/item_my_goal.xml
  app/src/main/res/layout/layout_my_header.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#80 [feat] 목표 수정 api 연동
  .github/workflows/pr_builder.yml
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/App.kt
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/request/RequestGoalContentTitle.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/di/NetworkModule.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/model/GoalContent.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/res/layout/activity_goal_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#84 [mod] 목표 추가, 수정 성공 시 토스트 띄우기
  .editorconfig
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#90 [fix] 목표 설정뷰 버그 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#91 [feat] 목표 상세 뷰 : 목표 보관api 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalKeep.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalKeepBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/dialog_bottom_goal_keep.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#82 [feat] 목표 달성 API 연동
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/request/RequestGoalAchievement.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalAchievement.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeMyGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/item_home_goal.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#92 [feat] 목표 상세 뷰 : 목표 삭제 API 연동
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalDeleted.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDeleteBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/res/layout/dialog_bottom_goal_delete.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#94 [feat] 홈 뷰 로티 추가
  app/build.gradle
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalDeleted.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/item_add_goal.xml
  app/src/main/res/raw/home_background.json
  app/src/main/res/raw/home_snail.json
Labels: 🐶 유빈 🐶, ✨ feat ✨

#95 [mod] 카카오 로그인 로직 수정
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/model/request/RequestAuth.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseAuth.kt
  app/src/main/java/org/keepgoeat/data/service/SignService.kt
  app/src/main/java/org/keepgoeat/di/SignModule.kt
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
Labels: 🐹 영진 🐹, 🛠 mod 🛠

#70 [mod] 로그인 로직 변경
  app/src/main/java/org/keepgoeat/data/service/SignService.kt
  app/src/main/java/org/keepgoeat/di/SignModule.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/res/layout/activity_sign.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#97 [feat] 스플래시에서 온보딩까지 화면 전환
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
Labels: 🐰 다은 🐰, ✨ feat ✨

#100 [fix] 로그인 연동 실패 버그 수정
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/datasource/local/SignSharedPreferences.kt
  app/src/main/java/org/keepgoeat/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/keepgoeat/data/model/request/RequestAuth.kt
  app/src/main/java/org/keepgoeat/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/KakaoAuthService.kt
  app/src/main/java/org/keepgoeat/di/NetworkModule.kt
  app/src/main/java/org/keepgoeat/di/SignModule.kt
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
Labels: 🐹 영진 🐹, ✨ feat ✨

#102 [chore] 마이페이지에서 백버튼 눌렀을 때 화면전환이 부자연스러운 버그
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalKeepBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#104 [feat] 토큰 재발급 api 연동
  app/build.gradle
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/org/keepgoeat/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseRefresh.kt
  app/src/main/java/org/keepgoeat/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/AuthService.kt
  app/src/main/java/org/keepgoeat/domain/repository/AuthRepository.kt
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#108 [mod] ui 배치 조정 및 터치 영역 수정
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/item_home_goal.xml
  app/src/main/res/layout/item_onboarding.xml
  app/src/main/res/layout/layout_my_header.xml
Labels: 🐹 영진 🐹, 🛠 mod 🛠

#107 [mod] 온보딩 버튼 텍스트 수정
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
  app/src/main/res/layout/item_onboarding.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#109 [mod] 홈 뷰 로티 파일 변경
  app/src/main/res/raw/home_background.json
  app/src/main/res/raw/home_snail.json
Labels: 🐶 유빈 🐶, 🛠 mod 🛠

#114 [mod] #112 HomeGoalViewType enum class 수정
  app/src/main/java/org/keepgoeat/presentation/home/HomeGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/type/HomeGoalViewType.kt
Labels: 🐶 유빈 🐶, 🛠 mod 🛠

#118 [fix] QA 반영
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/type/EatingType.kt
  app/src/main/res/drawable/ic_eating_less_tag_minus.xml
  app/src/main/res/drawable/ic_eating_more_tag_plus.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/view_eating_tag.xml
  app/src/main/res/values/strings.xml
Labels: 🕷 fix 🕷, 🐰 다은 🐰

#120 [fix] QA 반영
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_goal_setting.xml
  app/src/main/res/layout/item_home_goal.xml
  app/src/main/res/layout/item_my_goal.xml
Labels: 🕷 fix 🕷, 🐶 유빈 🐶

#122 [fix] QA 반영
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/datasource/remote/DummyDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/request/RequestData.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseListResult.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseResult.kt
  app/src/main/java/org/keepgoeat/data/repository/DummyRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/DummyService.kt
  app/src/main/java/org/keepgoeat/di/RepositoryModule.kt
  app/src/main/java/org/keepgoeat/di/ServiceModule.kt
  app/src/main/java/org/keepgoeat/domain/model/DummyData.kt
  app/src/main/java/org/keepgoeat/domain/repository/DummyRepository.kt
  app/src/main/java/org/keepgoeat/presentation/MainActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailTestActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalKeepBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/dummy/DummyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/dummy/DummyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/res/layout/activity_dummy.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_goal_detail_test.xml
  app/src/main/res/layout/activity_goal_setting.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_home_goal.xml
  app/src/main/res/layout/item_my_goal.xml
  app/src/main/res/values/strings.xml
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#124 [mod] 앱 아이콘 수정
  app/src/main/AndroidManifest.xml
  app/src/main/ic_keepgoeat-playstore.png
  app/src/main/res/drawable/ic_keepgoeat_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_keepgoeat.xml
  app/src/main/res/mipmap-anydpi-v26/ic_keepgoeat_round.xml
  app/src/main/res/mipmap-hdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-hdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-hdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-mdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-mdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-mdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-xhdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-xhdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-xxhdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-xxhdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-xxxhdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_keepgoeat_round.png
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#125 [fix] 리팩토링
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
Labels: 🕷 fix 🕷, 🐶 유빈 🐶

#128 [feat] #127 응원 메세지 줄바꿈 적용되도록 개행문자를 "\\n" -> "\n" 처리
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
Labels: 🐹 영진 🐹, ✨ feat ✨

#130 [fix] 목표 추가 버튼을 빠르게 연속 두번 클릭하면 동일한 목표가 두개 추가되는 버그
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/util/extension/ViewExt.kt
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#111 [feat] 온보딩 세번째 페이지에서 다음 버튼을 누르지 않고 앱을 이탈한 경우 온보딩 다시 띄우기
  app/build.gradle
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/KakaoAuthService.kt
  app/src/main/java/org/keepgoeat/di/SignModule.kt
  app/src/main/java/org/keepgoeat/domain/repository/AuthRepository.kt
  app/src/main/java/org/keepgoeat/presentation/SplashActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
Labels: 🐹 영진 🐹, ✨ feat ✨
