Repository Team-KeepGoEat/KeepGoEat-AOS, pull requests merged in 2023-03, with the labels that each got.

#171 [feat] 네트워크 연결 끊어진 상태일 때 에러메세지 보여주기
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseHomeContent.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/model/HomeContent.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/util/KGESnackbar.kt
  app/src/main/java/org/keepgoeat/util/NetworkMonitor.kt
  app/src/main/java/org/keepgoeat/util/binding/BindingActivity.kt
  app/src/main/res/layout/view_kge_snackbar.xml
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#181 [add] 토스트 메세지 추가
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/AccountInfoActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨, 😘 add 😘

#183 [mod] 목표 상세뷰의 목표 삭제 바텀 다이얼로그 ui 수정
  app/src/main/res/drawable/ic_trash.xml
  app/src/main/res/layout/dialog_bottom_goal_delete.xml
  app/src/main/res/layout/dialog_bottom_goal_keep.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#185 [feat] #184 네트워크 에러뷰 디자인 적용
  app/src/main/res/layout/view_kge_snackbar.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#187 [feat] 마이페이지 세뷰 메뉴 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/common/WebViewActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/ServiceIntroActivity.kt
  app/src/main/res/drawable-hdpi/img_service_intro_background.png
  app/src/main/res/drawable-hdpi/img_service_intro_logo.png
  app/src/main/res/drawable-xhdpi/img_service_intro_background.png
  app/src/main/res/drawable-xhdpi/img_service_intro_logo.png
  app/src/main/res/drawable-xxhdpi/img_service_intro_background.png
  app/src/main/res/drawable-xxhdpi/img_service_intro_logo.png
  app/src/main/res/drawable-xxxhdpi/img_service_intro_background.png
  app/src/main/res/drawable-xxxhdpi/img_service_intro_logo.png
  app/src/main/res/drawable/ic_detail_large.xml
  app/src/main/res/drawable/img_service_intro_background.png
  app/src/main/res/drawable/img_service_intro_logo.png
  app/src/main/res/layout/activity_service_intro.xml
  app/src/main/res/layout/activity_web_view.xml
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#188 [mod] 마이페이지 서비스 관련 링크 변경 및 문의 메일 내용 수정
  app/src/main/java/org/keepgoeat/presentation/common/WebViewActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/ServiceIntroActivity.kt
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#174 [feat] 탈퇴 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/model/WithdrawReason.kt
  app/src/main/java/org/keepgoeat/presentation/my/AccountInfoActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawReasonAdapter.kt
  app/src/main/java/org/keepgoeat/util/extension/ViewExt.kt
  app/src/main/res/drawable/ic_checkbox_checked.xml
  app/src/main/res/drawable/ic_checkbox_default.xml
  app/src/main/res/drawable/selector_edittext_withdraw.xml
  app/src/main/res/drawable/shape_cursor.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/dialog_withdraw.xml
  app/src/main/res/layout/item_withdraw.xml
  app/src/main/res/values/strings.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#190 [mod] 마이페이지, 목표 보관뷰 수정
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#192 [mod] 목표 보관뷰 목표 추가 버튼 가시성 조절
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/res/layout/activity_achieved_goal.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#195 [del] 목표 보관뷰, 홈 뷰에서 기준 삭제
  app/src/main/java/org/keepgoeat/data/model/response/ResponseAchievedGoal.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseHomeContent.kt
Labels: 🐶 유빈 🐶, 🧹 del 🧹

#196 [refactor] 탈퇴뷰 리팩토링
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawReasonAdapter.kt
  app/src/main/res/drawable/ic_checkbox_unchecked.xml
  app/src/main/res/drawable/selector_checkbox.xml
  app/src/main/res/layout/activity_withdraw.xml
  app/src/main/res/layout/item_withdraw.xml
  app/src/main/res/values/themes.xml
Labels: 🐹 영진 🐹, ✨ feat ✨, ✂refactor✂

#198 [fix] 회원탈퇴 성공 후 로그인화면으로 이동했을 때 백버튼을 누르면 다시 회원탈퇴 화면이 보이는 버그 수정
  app/src/main/java/org/keepgoeat/data/interceptor/AuthInterceptor.kt
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawDialogFragment.kt
Labels: 🕷 fix 🕷, 🐹 영진 🐹

#200 [feat] 마이페이지 api 연동
  app/src/main/java/org/keepgoeat/data/datasource/remote/UserDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseUserInfo.kt
  app/src/main/java/org/keepgoeat/data/repository/UserRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/UserService.kt
  app/src/main/java/org/keepgoeat/di/RepositoryModule.kt
  app/src/main/java/org/keepgoeat/di/ServiceModule.kt
  app/src/main/java/org/keepgoeat/domain/model/UserInfo.kt
  app/src/main/java/org/keepgoeat/domain/repository/UserRepository.kt
  app/src/main/java/org/keepgoeat/presentation/my/AccountInfoActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/layout/activity_my.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#203 [mod] 목표 설정할 때 특수문자 에러 수정
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#205 [feat] 탈퇴 뷰 직접입력 클릭했을 때 깜빡이는 이슈 해결
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawActivity.kt
  app/src/main/res/layout/activity_withdraw.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#206 [feat] 2차 QA 반영
  app/src/main/ic_keepgoeat-playstore.png
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/ServiceIntroActivity.kt
  app/src/main/res/drawable/shape_border_radius_16.xml
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/layout/activity_goal_detail.xml
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/activity_service_intro.xml
  app/src/main/res/layout/item_goal_sticker.xml
  app/src/main/res/mipmap-hdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-hdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-hdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-mdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-mdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-mdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-xhdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-xhdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-xxhdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-xxhdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_keepgoeat_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_keepgoeat.png
  app/src/main/res/mipmap-xxxhdpi/ic_keepgoeat_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_keepgoeat_round.png
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/themes.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#207 [mod] 목표 설정뷰 에러 메시지 노출 시점 수정
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/res/layout/activity_goal_setting.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#209 [fix] 토큰 갱신 성공 후 api 재요청할 경우, 400 에러가 뜨는 버그 수정
  app/src/main/java/org/keepgoeat/data/interceptor/AuthInterceptor.kt
Labels: 🕷 fix 🕷

#213 [fix] 네트워크 연결 상태에서도 종종 네트워크 에러뷰가 보이는 버그 수정
  app/src/main/java/org/keepgoeat/util/NetworkMonitor.kt
Labels: 🕷 fix 🕷, 🐹 영진 🐹
