Repository Team-KeepGoEat/KeepGoEat-AOS, pull requests merged in 2023-04, with the labels that each got.

#211 [mod] 탈퇴 뷰 API 수정
  app/src/main/java/org/keepgoeat/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/org/keepgoeat/data/service/AuthService.kt
Labels: 🐶 유빈 🐶, 🛠 mod 🛠

#218 [feat] 믹스패널 초기 세팅 및 Sign 이벤트 로그 찍기
  .github/workflows/pr_builder.yml
  app/build.gradle
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/service/KakaoAuthService.kt
  app/src/main/java/org/keepgoeat/data/service/NaverAuthService.kt
  app/src/main/java/org/keepgoeat/presentation/model/MixPanelEvent.kt
  app/src/main/java/org/keepgoeat/presentation/my/LogoutDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/LoginPlatformType.kt
  app/src/main/java/org/keepgoeat/presentation/type/SocialLoginType.kt
  app/src/main/java/org/keepgoeat/presentation/withdraw/WithdrawDialogFragment.kt
  app/src/main/java/org/keepgoeat/util/mixpanel/MixpanelProvider.kt
  app/src/main/java/org/keepgoeat/util/mixpanel/SignEvent.kt
Labels: 🐹 영진 🐹, ✨ feat ✨

#216 [feat] 강제 업데이트 구현
  app/src/main/java/org/keepgoeat/data/datasource/remote/VersionDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseVersion.kt
  app/src/main/java/org/keepgoeat/data/repository/VersionRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/VersionService.kt
  app/src/main/java/org/keepgoeat/di/RepositoryModule.kt
  app/src/main/java/org/keepgoeat/di/ServiceModule.kt
  app/src/main/java/org/keepgoeat/domain/repository/VersionRepository.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeForceUpdateDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/dialog_force_update.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#221 [feat] 믹스패널 목표 관련 이벤트 추가 및 수정
  app/src/main/java/org/keepgoeat/presentation/common/BaseViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/common/MixpanelViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDeleteBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalKeepBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/my/ServiceIntroActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/java/org/keepgoeat/util/mixpanel/GoalEvent.kt
  app/src/main/java/org/keepgoeat/util/mixpanel/MixpanelProvider.kt
  app/src/main/java/org/keepgoeat/util/mixpanel/SignEvent.kt
Labels: 🐹 영진 🐹, 🛠 mod 🛠, 😘 add 😘

#223 [mod] 강제 업데이트 다이얼로그 띄우기 로직 및 뷰 수정
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeForceUpdateDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/res/layout/dialog_force_update.xml
Labels: 🐹 영진 🐹, 🛠 mod 🛠

#224 [feat] 믹스패널 연결
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeBottomDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/my/AccountInfoActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/ArchivedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/withdraw/WithdrawActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/withdraw/WithdrawDialogFragment.kt
  app/src/main/java/org/keepgoeat/util/extension/ViewExt.kt
  app/src/main/java/org/keepgoeat/util/mixpanel/GoalEvent.kt
Labels: 🐶 유빈 🐶, ✨ feat ✨

#225 [refactor] 전반적인 코드 리팩토링
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/ApiResult.kt
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/request/RequestEditedGoalContent.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/AuthService.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/data/service/VersionService.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeForceUpdateDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/archive/ArchivedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/archive/ArchivedGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/archive/ArchivedGoalHeaderAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/java/org/keepgoeat/util/ApiUtil.kt
  app/src/main/java/org/keepgoeat/util/Event.kt
  app/src/main/java/org/keepgoeat/util/EventObserver.kt
  app/src/main/java/org/keepgoeat/util/NetworkMonitor.kt
  app/src/main/java/org/keepgoeat/util/extension/LivedataExt.kt
  app/src/main/res/layout/activity_archived_goal.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/text_appearance.xml
  app/src/main/res/values/themes.xml
Labels: 🐹 영진 🐹, ✂refactor✂

#227 [feat] 디버그 모드에서 이벤트 로그 찍히지 않도록 예외처리
  app/src/main/java/org/keepgoeat/util/mixpanel/MixpanelProvider.kt
Labels: 🐹 영진 🐹, ✨ feat ✨

#231 [feat] 3차 QA 반영
  app/src/main/java/org/keepgoeat/presentation/common/WebViewActivity.kt
  app/src/main/res/layout/dialog_bottom_goal_delete.xml
  app/src/main/res/layout/dialog_bottom_goal_keep.xml
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨, 🛠 mod 🛠
