Repository Team-KeepGoEat/KeepGoEat-AOS, pull requests merged in 2023-02, with the labels that each got.

#139 [refactor] 디테일 뷰 리팩토링
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
Labels: 🐹 영진 🐹, ✂refactor✂

#141 [refactor] 마이페이지 리팩토링
  app/src/main/java/org/keepgoeat/data/datasource/remote/MyDataSource.kt
  app/src/main/java/org/keepgoeat/data/repository/MyRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/MyService.kt
  app/src/main/java/org/keepgoeat/domain/repository/MyRepository.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
Labels: 🐹 영진 🐹, ✂refactor✂

#143 [refactor] 목표 추가뷰 리팩토링
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/java/org/keepgoeat/util/extension/FlowExt.kt
Labels: 🐹 영진 🐹, ✂refactor✂

#145 [refactor] 온보딩 뷰 리팩토링
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingActivity.kt
  app/src/main/java/org/keepgoeat/presentation/onboarding/OnboardingViewModel.kt
  app/src/main/res/drawable/default_dot.xml
  app/src/main/res/drawable/selected_dot.xml
  app/src/main/res/drawable/selector_tab_dot.xml
  app/src/main/res/drawable/shape_selected_dot.xml
  app/src/main/res/drawable/shape_unselected_dot.xml
  app/src/main/res/layout/activity_onboarding.xml
Labels: 🐰 다은 🐰, ✂refactor✂

#134 [feat] 네이버 로그인 구현
  app/build.gradle
  app/src/main/java/org/keepgoeat/data/service/NaverAuthService.kt
  app/src/main/java/org/keepgoeat/di/SignModule.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_naver.xml
  app/src/main/res/layout/activity_sign.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, ✨ feat ✨

#147 네이버 로그인 api 연동
  app/src/main/java/org/keepgoeat/data/service/AuthService.kt
  app/src/main/java/org/keepgoeat/data/service/NaverAuthService.kt
Labels: 🐰 다은 🐰, ✨ feat ✨

#149 [refactor] 로그인 뷰 리팩토링
  app/src/main/java/org/keepgoeat/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/org/keepgoeat/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/AuthService.kt
  app/src/main/java/org/keepgoeat/data/service/KakaoAuthService.kt
  app/src/main/java/org/keepgoeat/data/service/NaverAuthService.kt
  app/src/main/java/org/keepgoeat/domain/repository/AuthRepository.kt
Labels: 🐰 다은 🐰, ✂refactor✂

#151 [refactor] 목표 상세 뷰 Flow 리팩토링
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalDeleted.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalKeep.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalKeepBottomDialogFragment.kt
Labels: 🐶 유빈 🐶, ✂refactor✂

#133 [refactor] 홈 뷰 버튼 중복클릭 방지
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeGoalAdapter.kt
  app/src/main/res/drawable/background_cheer_msg.xml
  app/src/main/res/drawable/background_goal_info.xml
  app/src/main/res/drawable/background_goal_list.xml
  app/src/main/res/drawable/background_sign_box.xml
  app/src/main/res/drawable/ic_my_page_white.xml
  app/src/main/res/drawable/ic_plate_gray.xml
  app/src/main/res/drawable/ic_snail_green_ribbon.xml
  app/src/main/res/drawable/ic_snail_orange_cheer_right.xml
  app/src/main/res/drawable/ic_snail_orange_hungry.xml
  app/src/main/res/drawable/ic_snail_orange_spoon_left.xml
  app/src/main/res/layout/activity_home.xml
  app/src/main/res/layout/dialog_bottom_goal_keep.xml
  app/src/main/res/layout/dialog_bottom_home.xml
  app/src/main/res/layout/item_add_goal.xml
  app/src/main/res/layout/item_home_goal.xml
Labels: 🐶 유빈 🐶, ✂refactor✂

#153 [feat] 로그아웃 및 회원 탈퇴 구현
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/datasource/remote/AuthDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseWithdraw.kt
  app/src/main/java/org/keepgoeat/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/AuthService.kt
  app/src/main/java/org/keepgoeat/data/service/KakaoAuthService.kt
  app/src/main/java/org/keepgoeat/data/service/NaverAuthService.kt
  app/src/main/java/org/keepgoeat/di/SignModule.kt
  app/src/main/java/org/keepgoeat/domain/repository/AuthRepository.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/SocialLoginType.kt
  app/src/main/java/org/keepgoeat/util/extension/ActivityExt.kt
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/values/strings.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#155 [feat] 마이페이지 ui 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/AccountInfoActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalHeaderAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/LogoutDialogFragment.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/util/binding/BindingDialogFragment.kt
  app/src/main/res/drawable/ic_detail.xml
  app/src/main/res/layout/activity_account_info.xml
  app/src/main/res/layout/activity_achieved_goal.xml
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/dialog_logout.xml
  app/src/main/res/layout/item_achieved_goal.xml
  app/src/main/res/layout/layout_achieved_goal_header.xml
  app/src/main/res/layout/view_toolbar.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#157 [refactor] #156 툴바 레이아웃 재사용
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingActivity.kt
  app/src/main/res/layout/activity_achieved_goal.xml
  app/src/main/res/layout/activity_goal_setting.xml
Labels: 🐹 영진 🐹, ✂refactor✂

#135 [refactor] 홈 뷰 Flow 적용
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalAchievement.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeActivity.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/home/HomeViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/type/ProcessState.kt
  app/src/main/res/layout/activity_home.xml
Labels: 🐶 유빈 🐶, ✂refactor✂

#159 [mod] 목표 설정 뷰 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/res/color/selector_less_complete_button_color.xml
  app/src/main/res/color/selector_more_complete_button_color.xml
  app/src/main/res/layout/activity_goal_setting.xml
  app/src/main/res/values/strings.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#163 [mod] 홈 화면 조회 API 수정
  app/src/main/java/org/keepgoeat/data/model/response/ResponseHome.kt
Labels: 🐶 유빈 🐶, 🛠 mod 🛠

#161 [feat] 소셜 로그인에서 계정 정보 불러오기
  app/src/main/java/org/keepgoeat/data/datasource/local/KGEDataSource.kt
  app/src/main/java/org/keepgoeat/data/service/KakaoAuthService.kt
  app/src/main/java/org/keepgoeat/data/service/NaverAuthService.kt
  app/src/main/java/org/keepgoeat/domain/model/AccountInfo.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignActivity.kt
  app/src/main/java/org/keepgoeat/presentation/sign/SignViewModel.kt
  app/src/main/res/layout/activity_my.xml
Labels: 🐶 유빈 🐶, ✨ feat ✨

#167 [feat] 마이페이지 보관된 목표 수 보여주기 구현 및 관련 코드 정리
  app/src/main/java/org/keepgoeat/data/datasource/remote/GoalDataSource.kt
  app/src/main/java/org/keepgoeat/data/datasource/remote/MyDataSource.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseAchievedGoal.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/repository/MyRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/data/service/GoalService.kt
  app/src/main/java/org/keepgoeat/data/service/MyService.kt
  app/src/main/java/org/keepgoeat/di/RepositoryModule.kt
  app/src/main/java/org/keepgoeat/di/ServiceModule.kt
  app/src/main/java/org/keepgoeat/domain/model/AchievedGoal.kt
  app/src/main/java/org/keepgoeat/domain/model/MyGoal.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/domain/repository/MyRepository.kt
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalActivity.kt
  app/src/main/java/org/keepgoeat/presentation/my/AchievedGoalAdapter.kt
  app/src/main/java/org/keepgoeat/presentation/my/MyViewModel.kt
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/item_achieved_goal.xml
Labels: 🐹 영진 🐹, ✨ feat ✨

#165 [mod] 목표 설정, 목표 상세, 목표 수정 api 수정
  app/src/main/java/org/keepgoeat/data/model/request/RequestGoalContent.kt
  app/src/main/java/org/keepgoeat/data/model/request/RequestGoalContentTitle.kt
  app/src/main/java/org/keepgoeat/data/model/response/ResponseGoalDetail.kt
  app/src/main/java/org/keepgoeat/data/repository/GoalRepositoryImpl.kt
  app/src/main/java/org/keepgoeat/domain/model/GoalDetail.kt
  app/src/main/java/org/keepgoeat/domain/repository/GoalRepository.kt
  app/src/main/java/org/keepgoeat/presentation/detail/GoalDetailActivity.kt
  app/src/main/java/org/keepgoeat/presentation/model/GoalContent.kt
  app/src/main/java/org/keepgoeat/presentation/setting/GoalSettingViewModel.kt
  app/src/main/res/layout/activity_goal_detail.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠

#170 [mod] 카카오 로그인 닉네임 받아오기
  app/src/main/java/org/keepgoeat/data/service/KakaoAuthService.kt
  app/src/main/res/layout/activity_account_info.xml
Labels: 🐶 유빈 🐶, 🛠 mod 🛠

#179 [mod] 목표 상세뷰 ui 수정 및 목표 기준 추가
  app/src/main/res/layout/activity_goal_detail.xml
Labels: 🐰 다은 🐰, 🛠 mod 🛠
